[package]
name = "double-ratchet-2"
authors = ["Hannes Furmans"]
description = "Implementation of Double Ratchet as specified by Signal."
homepage = "https://github.com/Dione-Software/double-ratchet-2"
repository = "https://github.com/Dione-Software/double-ratchet-2"
readme = "README.md"
keywords = ["double-ratchet", "crypto", "cryptography", "signal"]
version = "0.3.5"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }


[dependencies]
p256 = {version = "0.9", features = ["zeroize", "ecdh", "arithmetic", "pem", "jwk"]}
rand_core = {version = "0.6"}
getrandom = {version = "0.2.3"}
hkdf = "0.12.0"
hmac = "0.11.0"
aes-gcm-siv = {version = "0.10.3"}
ring-compat = {version = "0.4.0", optional = true, features = ["digest"]}
sha2 = {version = "0.9.5", optional = true}
serde = {version = "1.0.125", default-features = false, features = ["derive"]}
serde_bytes = "0.11.5"
bincode = "1.3.3"
hashbrown = {version = "0.11.2", features = ["serde"]}
zeroize = {version = "1.3", features = ["zeroize_derive"]}
const-oid = "0.7.0"

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "double_ratchet_bench"
harness = false

[profile.release]
lto = true
opt-level = 3

[features]
default = ["sha2"]
ring = ["ring-compat/digest"]
wasm = ["getrandom/js"]