[package]
name = "double-ratchet-2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x25519-dalek = "1.1.1"
rand_core = "0.5"
hkdf = "0.11.0"
hmac = "0.11.0"
aes-gcm-siv = {version = "0.10.0"}
ring-compat = {version = "0.2.1", features = ["digest"]}
serde = {version = "1.0.125", default-features = false, features = ["derive"]}
serde_bytes = "0.11.5"
bincode = "1.3.3"
hashbrown = "0.11.2"

[profile.release]
lto = true
opt-level = 3